### ISSUE TITLE
2.3.0 ActorSelection tell with no sender causes Compilation error

### ISSUE THREAD

**Issue by njovy** [playframework/playframework#3058]
I recently migrated my play project to 2.3.0 from 2.2.2. I also updated my build.sbt to use the upper version of Scala, 2.11.1. 
The below code works fine in 2.2.2 but it fails to compile in 2.3.0.

```
Akka.system().actorSelection(ActorPaths.EVENT_SOURCE_MANAGER_PATH).tell(new EventSourceSendDataTemplate(to, n)); 
```

Do I have to provide a sender actor reference since 2.3.0?
