### ISSUE TITLE
org.apache.commons.codec.digest.DigestUtils.sha1Hex error after migration to play 2.5.15 from 2.3.x

### ISSUE THREAD

**Issue by mullex** [playframework/playframework#7416]
```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[RuntimeException: java.lang.NoSuchMethodError: org.apache.commons.codec.digest.DigestUtils.sha1Hex(Ljava/lang/String;)Ljava/lang/String;]]
    at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:293)
    at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
    at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
    at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
    at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:100)
    at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
    at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
    at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
    at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
Caused by: java.lang.NoSuchMethodError: org.apache.commons.codec.digest.DigestUtils.sha1Hex(Ljava/lang/String;)Ljava/lang/String;
    at play.api.libs.Codecs$.sha1(Codecs.scala:35)
    at controllers.AssetInfo$$anonfun$5$$anonfun$apply$3.apply(Assets.scala:193)
    at controllers.AssetInfo$$anonfun$5$$anonfun$apply$3.apply(Assets.scala:193)
    at scala.Option.map(Option.scala:146)
    at controllers.AssetInfo$$anonfun$5.apply(Assets.scala:193)
    at controllers.AssetInfo$$anonfun$5.apply(Assets.scala:193)
    at scala.Option.orElse(Option.scala:289)
    at controllers.AssetInfo.<init>(Assets.scala:193)
    at controllers.Assets$$anonfun$controllers$Assets$$assetInfoFromResource$1$$anonfun$apply$4.apply(Assets.scala:293)
    at controllers.Assets$$anonfun$controllers$Assets$$assetInfoFromResource$1$$anonfun$apply$4.apply(Assets.scala:290)
```

**Comment by gmethvin** [comment]
@mullex It would be helpful if you could provide a small sample that reproduces the bug. To me it looks like you maybe have an incompatible version of the commons-codec library being brought in by another library or SBT plugin, so it's probably not actually a Play bug.

**Comment by marcospereira** [comment]
Hey @mullex, this is a problem with your project using an old version of `commons-codec` dependency. Play 2.5.15 depends on `commons-codec` version `1.10`, as you can see here:

https://github.com/playframework/playframework/blob/2.5.15/framework/project/Dependencies.scala#L128

It is possible that your project or some other dependency is forcing another version which is not compatible with Play. You can use [sbt-dependency-graph](https://github.com/jrudolph/sbt-dependency-graph) to inspect your project dependencies and see better what is happening. I also recommend that you do a `sbt clean` to ensure that no old build results are interfering with the update.

Finally, the [mailing list](https://groups.google.com/forum/#!forum/play-framework) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help. That said, I'm closing this and we can discuss further in the mailing list.

Thanks.
