### ISSUE TITLE
upgrade to Akka 2.5.12?

### ISSUE THREAD

**Issue by SethTisue** [playframework/playframework#8404]
Play is failing to compile in the Scala 2.12 community build, at e.g. https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/2857/

I suspect the problem is https://github.com/akka/akka/pull/24827 which was included in Akka 2.5.12. Play is still on 2.5.11.

Could y'all upgrade to 2.5.12...?

(Or, if you look into it and the dependency declaration changes turn out to be problematic for Play and you need to stay on 2.5.11, then 1) you should talk to the Akka team about it, and 2) I could freeze Akka at 2.5.11 for now in the community build.)

**Comment by SethTisue** [comment]
if I try the upgrade locally (on either 2.12.4 or 2.12.6, doesn't matter) I get the same compilation error I'm seeing in the community build:

```
[error] /Users/tisue/playframework/framework/src/play-streams/src/test/scala/play/api/libs/streams/AccumulatorSpec.scala:109: type mismatch;
[error]  found   : akka.stream.javadsl.Sink[Nothing,java.util.concurrent.CompletionStage[Int]]
[error]  required: akka.stream.javadsl.Sink[E,java.util.concurrent.CompletionStage[Int]]
[error] Note: Nothing <: E, but class Sink is invariant in type In.
[error] You may wish to define In as +In instead. (SLS 4.5)
[error]         await(play.libs.streams.Accumulator.fromSink(sum.toSink.mapMaterializedValue(FutureConverters.toJava).asJava).asScala().run(source)) must_== 6
[error]                                                                                                               ^
[error] /Users/tisue/playframework/framework/src/play-streams/src/test/scala/play/api/libs/streams/AccumulatorSpec.scala:187: type mismatch;
[error]  found   : akka.stream.javadsl.Sink[Nothing,java.util.concurrent.CompletionStage[Int]]
[error]  required: akka.stream.javadsl.Sink[E,java.util.concurrent.CompletionStage[Int]]
[error] Note: Nothing <: E, but class Sink is invariant in type In.
[error] You may wish to define In as +In instead. (SLS 4.5)
[error]           await(play.libs.streams.Accumulator.fromSink(sum.toSink.mapMaterializedValue(FutureConverters.toJava).asJava).asScala().run(source)) must_== 6
[error]                                                                                                                 ^
[error] /Users/tisue/playframework/framework/src/play-streams/src/test/scala/play/api/libs/streams/AccumulatorSpec.scala:235: type mismatch;
[error]  found   : akka.stream.javadsl.Sink[Nothing,java.util.concurrent.CompletionStage[Int]]
[error]  required: akka.stream.javadsl.Sink[E,java.util.concurrent.CompletionStage[Int]]
[error] Note: Nothing <: E, but class Sink is invariant in type In.
[error] You may wish to define In as +In instead. (SLS 4.5)
[error]           await(play.libs.streams.Accumulator.fromSink(sum.toSink.mapMaterializedValue(FutureConverters.toJava).asJava).asScala().run(6)) must_== 6
[error]                                                                                                                 ^
[error] /Users/tisue/playframework/framework/src/play-streams/src/test/scala/play/libs/streams/AccumulatorSpec.scala:91: overloaded method value run with alternatives:
[error]   (x$1: Int,x$2: akka.stream.Materializer)java.util.concurrent.CompletionStage[Int] <and>
[error]   (x$1: akka.stream.javadsl.Source[Int, _],x$2: akka.stream.Materializer)java.util.concurrent.CompletionStage[Int]
[error]  cannot be applied to (akka.stream.javadsl.Source[Nothing,akka.NotUsed], akka.stream.Materializer)
[error]         await(fAcc.run(errorSource, m)) must throwA[ExecutionException].like {
[error]                    ^
[error] four errors found
```

**Comment by SethTisue** [comment]
see also https://github.com/akka/akka-http/issues/2009

**Comment by schmitch** [comment]
actually for akka-stream 2.5.12 the Scala 2.13.0-M3 dependency is missing https://mvnrepository.com/artifact/com.typesafe.akka/akka-stream and play already cross builds for it

**Comment by schmitch** [comment]
@sethtisue you can try out my branch as long as there is no scala 2.13.0-M3(or M4) for akka 2.5.12 : https://github.com/schmitch/playframework/tree/fix-8404 guess it should work

**Comment by ktoso** [comment]
> actually for akka-stream 2.5.12 the Scala 2.13.0-M3 dependency is missing https://mvnrepository.com/artifact/com.typesafe.akka/akka-stream and play already cross builds for it

Please ping us (can be me or @raboof since Johannes is still offline a bit) whenever something is missing like that :)

**Comment by raboof** [comment]
Thanks for the ping - I think I saw this somewhere earlier but it dropped off the radar. Akka 2.5.12 for scala 2.13.0-M3 should now be making its way to maven central. For 2.13.0-M4 we still have some dependencies that aren't ready, but we're tracking that in https://github.com/akka/akka/issues/25105. Akka HTTP should already be there.

**Comment by schmitch** [comment]
@SethTisue we merged the PR into master you can unfreeze play now.

**Comment by SethTisue** [comment]
> @SethTisue we merged the PR into master you can unfreeze play now.

done, and I moved our Akka tag up to `v2.5.13`
