### ISSUE TITLE
Play 2.8.2 AkkaHttpServe doesn't work with latest version of akka-http (10.2.0)

### ISSUE THREAD

**Issue by rodrigotn** [playframework/playframework#10414]
Using play `2.8.2` with the latest version of akka-http `10.2.0` I'm getting a class not found exception:

```
INFO play.api.Play Application started (Prod) (no global state) 
Exception in thread "main" java.lang.NoClassDefFoundError: akka/http/javadsl/UseHttp2
        at play.core.server.AkkaHttpServerProvider.createServer(AkkaHttpServer.scala:664)
        at play.core.server.AkkaHttpServerProvider.createServer(AkkaHttpServer.scala:662)
        at play.core.server.ServerProvider.createServer(ServerProvider.scala:29)
        at play.core.server.ServerProvider.createServer$(ServerProvider.scala:26)
        at play.core.server.AkkaHttpServerProvider.createServer(AkkaHttpServer.scala:662)
        at play.core.server.ProdServerStart$.start(ProdServerStart.scala:60)
        at play.core.server.ProdServerStart$.main(ProdServerStart.scala:30)
        at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Caused by: java.lang.ClassNotFoundException: akka.http.javadsl.UseHttp2
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 8 more
```

Thanks!

**Comment by mkurz** [comment]
See #10411, seems like you have to wait for Play 2.9

**Comment by alternegro** [comment]
@rodrigotn do you get this issue only in Dev mode?

**Comment by raboof** [comment]
Possibly, but not necessarily: `UseHttp2` has been deprecated in Akka HTTP 10.1.x and removed in 10.2.x. If we can avoid referring to it in Play, then downstream projects should be able to update to Akka HTTP 10.2.x even if Play is still on 10.1.x.

Play uses UseHttp2 to implement the `http2.alwaysForInsecure` option. This option was introduced because back then it was not possible to have 'h2c via Upgrade' and 'h2c with prior knowledge' on the same port. However, since at least Akka HTTP 10.1.10, it is actually possible (and the default behaviour when HTTP/2 is enabled) to have both h2c via 'Upgrade' and h2c via 'prior knowledge' on the same port.

Since Play 2.8 is already on 10.1.12, I think we can remove the `http2.alwaysForInsecure` feature and all references to `UseHttp2`, and that should make Play 2.8 usable with Akka HTTP 10.2 as well. I'll give it a try.

**Comment by raboof** [comment]
This code was already removed for 2.9 in a23b5debe1da6d09905f9406ee690bac36c0b6c7, so this might just be a matter of backporting #9980

**Comment by mkurz** [comment]
@raboof Can you we close this issue now that #10427 was merged? (For some reason GitHub did not auto-close it...)
Also I don't think we will upgrade akka-http to version 10.2.0 in the 2.8.x branch, but people should override the dependency themselves?

**Comment by raboof** [comment]
> Can you we close this issue now that #10427 was merged?

I think so, yes!

> Also I don't think we will upgrade akka-http to version 10.2.0 in the 2.8.x branch, but people should override the dependency themselves?

Indeed!

**Comment by imanabu** [comment]
Note: The similar error messages will occur when you have accidentally left in:

           play.server.provider="play.core.server.akkahttp.AkkaHttpServerProvider"

This will likely be forgotten if you are migrating and previously manually enabled the Akka HTTP.
