### ISSUE TITLE
Play Framework (play-scala-seed) does not compile with sbt 1.3.0-RC1

### ISSUE THREAD

**Issue by henricook** [playframework/playframework#9321]
sbt 1.3.0-RC1 is due to final release in the next couple of weeks

This morning I did:

`sbt new playframework/play-scala-seed.g8` [Accept all default options]
`echo "sbt.version=1.3.0-RC1" >> play-scala-seed/project/build.properties`
`cd play-scala-seed`
`sbt compile`

and received this error:

```
[info] Compiling 5 Scala sources and 1 Java source to /home/henri/repos/play-scala-seed/target/scala-2.12/classes ...
[error] /home/henri/repos/play-scala-seed/app/controllers/HomeController.scala:22:19: object index is not a member of package views.html
[error]     Ok(views.html.index())
[error]                   ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

Java version: OpenJDK8 (8u212-b03-0ubuntu1.19.04.2)

Anecdotally I have the same issue with view compilation (/dynamic code generation)? With sbt 1.3.0-RC1 on a much larger project and no other prominent errors

I'm afraid i have no idea how dynamic code generation works in Play, does anyone have any idea what it could be?

**Comment by mkurz** [comment]
See https://github.com/sbt/sbt/issues/4681

**Comment by mkurz** [comment]
Also https://github.com/playframework/twirl/pull/215

**Comment by henricook** [comment]
Thanks, should we keep this issue open?

**Comment by dwijnand** [comment]
Yep, let's track this.

**Comment by jtjeferreira** [comment]
I can report that this is fixed in sbt 1.3.0-M5. However I still cant run the app (see #9368)

**Comment by marcospereira** [comment]
> I can report that this is fixed in sbt 1.3.0-M5.

Wait, so it works with M5 but does not work with RC1?

**Comment by jtjeferreira** [comment]
> > I can report that this is fixed in sbt 1.3.0-M5.
> 
> Wait, so it works with M5 but does not work with RC1?
As far as I understand M5 is more recent than RC1...

**Comment by dwijnand** [comment]
All fixed
