### ISSUE TITLE
[2.4] Document how to integrate Spring Framework DI

### ISSUE THREAD

**Issue by elvenking** [playframework/playframework#4665]
I can't find a solution for integrating Spring Framework as a DI engine. I simply can't migrate to Guice.

Please, document how to use Spring instead of Guice.

**Comment by matiwinnetou** [comment]
Integration with Spring doesn't exist yet, there is only a prototype done by James Ropper:
https://github.com/jroper/play-spring

It is unfinished and needs to be adopted. Since play is open source, your contributions (pull requests) would be welcome.

Community members however tried to integrate Guice with Spring as a way to migrate to Play 2.4. I would consider such solution far from ideal but it may be a short term solution.

https://github.com/spring-projects/spring-guice

**Comment by elvenking** [comment]
OK, thanks for info.  I will try Spring-Guice.

**Comment by matiwinnetou** [comment]
cool, closing the issue would be appreciated as there is not much Play team can do as this is not an issue with Play itself.

**Comment by elvenking** [comment]
I am sure it should not be closed. The problem is still not resolved.

**Comment by jroper** [comment]
This isn't a problem, it's a feature request, and one that we do not want to implement in the core of Play.  We provide support for Guice out of the box, we're not going to provide support for every DI provider out of the box, that would be a waste of our time.  We've specifically left spring support as something that someone in the community can provide.  If it means that much to you, then you should implement it.

**Comment by jtdev** [comment]
@jroper the problem is that integrating Spring DI in Play < 2.4 was easy, but in 2.4 it is extremely hard, even though Play 2.4 is featuring "JSR 330 Dependency Injection" support as an "Out of the box" feature whereas <2.4 did not.

The result is that "Dependency Injection" in Play 2.4 is NOT a feature, it is an internal Play 2.4 mechanism that made it more difficult to integrate other JSR 330 DI solutions for clients.

**Comment by jtdev** [comment]
Here's more info about attempts to get it to work in 2.4: https://groups.google.com/forum/#!topic/play-framework/hFOtzSNSDsQ

**Comment by jroper** [comment]
@jtdev why spend so much energy complaining? This is an open source project, why not focus that energy on something productive like implementing spring support?

**Comment by gmethvin** [comment]
For anyone who finds this issue, the currently most mature implementation of spring support seems to be https://github.com/remithieblin/play-spring-loader. If you have additional questions, please ask on the mailing list (Play does not officially support Spring but we're happy to help third-party devs with the Play aspects).

**Comment by AlNedorezov** [comment]
@gmethvin is there a solution that works with play 2.6?
I have tried https://github.com/remithieblin/play-spring-loader, but doesn't work with 2.6, as it gives the following internal server error, for (GET) [/]:

```
NoSuchMethodError: play.api.Environment$.simple$default$2()Lscala/Enumeration$Value;
No source available, here is the exception stack trace:
->java.lang.NoSuchMethodError: play.api.Environment$.simple$default$2()Lscala/Enumeration$Value;
     com.actimust.play.spring.SpringApplicationBuilder.<init>(SpringApplicationBuilder.scala:26)
     com.actimust.play.spring.SpringApplicationLoader.<init>(SpringApplicationLoader.scala:16)
```

**Comment by marcospereira** [comment]
Hi @AlNedorezov, we don't have an official module to support Spring and [remithieblin/play-spring-loader](https://github.com/remithieblin/play-spring-loader) is what we usually recommend. But looks like it does not supports Play 2.6 yet.

Right now we don't have time to help to maintain the project, so maybe you can submit a PR there?

**Comment by AlNedorezov** [comment]
@marcospereira Thanks for a quick reply.
I'll see what I can do.
