### ISSUE TITLE
Provide a post() method on WS for POSTing multipart/form-data

### ISSUE THREAD

**Issue by studiodev** [playframework/playframework#902]
There is actually no way to post a multipart/form-data, without encoding manually the body (and this is tricky!)

It's sad to not have a WS method which allow to call a controller like the "[File upload example](http://www.playframework.com/documentation/2.1.0/ScalaFileUpload)"

**Comment by naderghanbari** [comment]
Is there any plan to fix this?

**Comment by cdmckay** [comment]
I wrote a Writeable to use the existing MultipartFormData object for POSTing multipart form data:

https://gist.github.com/cdmckay/4b269e9017a30111556a

And here's an example of usage:

https://gist.github.com/cdmckay/5f05cbcb5327259df1cf

So you just need to drop it in and it should work with the existing WS flow.

**Comment by brianwawok** [comment]
@cdmckay do you have a version that works in play 2.4?  I had my own home rolled attempt, but so far  all my multipart form posts using play get back a "The request body is too large" from my API I am hitting..

**Comment by david-bouyssie** [comment]
@cdmckay : is there a solution to observe the progression of the upload ?
Currently I'm using scalaj-http for this purpose (https://github.com/scalaj/scalaj-http) but I would like to switch to Play WS in order to avoid extra dependencies and use asynchronous requests.
Thanks !

**Comment by ergomesh** [comment]
@brianwawok

I have a similar problem I am migrating from 2.3 to 2.4 and get this now

Compilation error[object multipart is not a member of package com.ning.http] using the@cdmckay example. Anyone have this working in play2.4.x ?

**Comment by brianwawok** [comment]
@ergomesh yes I was able to make this work in 2.4.  I had to forcibly override my async http client version to 1.9.29, and then I did:

https://gist.github.com/brianwawok/eb9ac542eb7b4795ac06

**Comment by evanzeng** [comment]
@biranwawok Hi! I am in China and I can't open the link
https://gist.github.com/brianwawok/eb9ac542eb7b4795ac06
Would you please post your solution to my email: evanzeng@qq.com? Thanks a lot!

**Comment by mkurz** [comment]
+1

**Comment by mkurz** [comment]
Could someone provide a pull request? This would be great!

**Comment by brianwawok** [comment]
@mkurz i have it in a hack state with no tests, not sure I am going to have time to clean up into a proper PR

**Comment by mkurz** [comment]
@brianwok If you could find some time to submit that PR that would be really awesome and would make some people really happy! :smile!

**Comment by mkurz** [comment]
@brianwawok If you do some work on this and provide a PR I could maybe help out testing things.

**Comment by jakob85** [comment]
Not sure if you guys fixed the issue but I answered my own question at stackoverflow and got it working.
http://stackoverflow.com/questions/35325942/timeout-when-sending-multipart-form-data-in-play2-2-4-6

**Comment by mkurz** [comment]
@jakob85 If you are keen to provide a pull request with implements this feature directly in Play you are welcome to.

**Comment by david-bouyssie** [comment]
A solution including the monitoring of upload progression would be really awesome.
This feature is provided by this library: https://github.com/scalaj/scalaj-http

**Comment by schmitch** [comment]
Actually all the solutions here would be missing the ending, i.e:
Something like that:
--BRY7v0J3h3fIl91lUeQ6SxMJWqNHbRYi4Exp2C3s--

What would actually work is using the asyncHttpClient.preparePost().addBodyPart funtionallity i.e.:
```
val asyncHttpClient: AsyncHttpClient = ws.client.underlying

        val postBuilder = asyncHttpClient.preparePost(url).addBodyPart(filePart).addBodyPart(textPart)
          .addHeader(AUTHORIZATION, s"Basic $auth")
        val request = postBuilder.build()

        val result = Promise[NingWSResponse]()
        asyncHttpClient.executeRequest(request, new AsyncCompletionHandler[AHCResponse]() {
          override def onCompleted(response: AHCResponse) = {
            result.success(NingWSResponse(response))
            response
          }

          override def onThrowable(t: Throwable) = {
            result.failure(t)
          }
        })
        result.future
```

Not sure if a Writeable has access to that.

**Comment by schmitch** [comment]
Actually it would be great if somebody could help me with the PR on tests.

Actually I've left out the documentation since I'm not sure if it's good to either have something like ``.post(Seq(part1, part2)) `` and on the Java part a List. Actually maybe somebody from the core team could give me some hints.

**Comment by mkurz** [comment]
Maybe we can can still get this into 2.5?

**Comment by gmethvin** [comment]
@mkurz At this point there should be no problem getting it into 2.5. It would only be an issue if there are major API changes.

**Comment by mkurz** [comment]
@gmethvin Cool! :smile:

**Comment by schmitch** [comment]
That would be great. I actually came across this since we are sending data to another provider which uses insecure SSL, so using the underlying AhcClient takes more work than just fixing this issue..

**Comment by david-bouyssie** [comment]
Could it be possible to have access to ```onContentWriteProgress``` callback or is it too complicated to interface it with the Play API ?
https://asynchttpclient.github.io/async-http-client/apidocs/com/ning/http/client/AsyncCompletionHandler.html#onContentWriteProgress%28long,%20long,%20long%29

This would be a very useful feature !

**Comment by david-bouyssie** [comment]
Do you have any tip to monitor the upload progress ?
Do I have to use the underlying client to achieve that ?
Thanks !

**Comment by AndreyIlin** [comment]
Is there any workaround for play 2.5?

**Comment by schmitch** [comment]
it will when 2.5.1 hit @AndreyIlin

**Comment by AndreyIlin** [comment]
Thanks @schmitch, waiting.

**Comment by sowmyamoracle** [comment]
Hi,
Am new to scala & play. Can someone help me for file upload to remote server. Am able to upload file, but looking for uploading file to remote server. 

I am trying to use WSClient as per below link, but am not succesful yet
https://www.playframework.com/documentation/2.5.x/ScalaWS 

working examples will help please. Am using play 2.2.0 with Scala 2.10.2 and sbt 0.13.11

**Comment by gmethvin** [comment]
@sowmyamoracle Your question doesn't seem to be related to this PR. It would probably be better to ask on the [mailing list](https://groups.google.com/forum/#!forum/play-framework).

**Comment by sowmyamoracle** [comment]
Thanks @gmethvin.

**Comment by dmbuchta** [comment]
Are there any examples on how to do this in java?
