### ISSUE TITLE
play-plugins-salat doesn't compile with play 2.2.1(ObjectId not found)

### ISSUE THREAD

**Issue by ghost** [playframework/playframework#2055]
Hello all,
this issue is related to closed defect #1678 . I spend the whole day and could not find fix, I am relatively new to play scala.

I use: 

object ApplicationBuild extends Build {

  val appName         = "play-angular"
  val appVersion      = "1.0-SNAPSHOT"

  val appDependencies = Seq(
    // Add your project dependencies here,
   // jdbc,
   // cache,
    "se.radley" %% "play-plugins-salat" % "1.4.0-SNAPSHOT"
    //"se.radley" %% "play-plugins-salat" % "1.4.0"
  )

  val main = play.Project(appName, appVersion, appDependencies).settings(
    routesImport += "se.radley.plugin.salat.Binders._",
    templatesImport += "org.bson.types.ObjectId",
    resolvers += Resolver.sonatypeRepo("snapshots")
  )

no build.sbt

plugins.sbt has:
// The Typesafe repository 
resolvers ++= Seq(
  "Typesafe Releases" at "http://repo.typesafe.com/typesafe/releases/",
  "Typesafe Snapshots" at "http://repo.typesafe.com/typesafe/snapshots/"
)

// Use the Play sbt plugin for Play projects
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.2.1")

I took sample of the project from https://github.com/leon/play-salat/tree/wip/1.4.0
my scala is v2.10.2
play 2.2.1

I am getting compilation error: [error] C:\MyProject\ideawrkspace\myproject\conf\routes:10: not found: type Obje
ctId

same problem with  play-plugins-salat v1.3.0

I also have conf/play.plugins with:
#500:se.radley.plugin.salat.SalatPlugin

I also tried to add 
play-plugins-salat_2.10-1.4.0-SNAPSHOT.jar and mongo-java-driver-2.11.2.jar to my project\lib

tried to do everything as per https://github.com/leon/play-salat/ wiki guide :(

in target...\routes_routing.scala has only those imports:
import play.core._
import play.core.Router._
import play.core.j._

import play.api.mvc._

import Router.queryString 

I am desperate and don't know what to try next, please give me any advise!!!
