### PR TITLE
rollback 8213 causing chrome favicon.ico request to recompile

### LINKED ISSUE #7753: Compile error triggers multiple compilations
Normally, when I screw up my code and "run" my app, refreshing the web browser causes play to compile, fail, and return a "Compilation failed" page. Since upgrading to 2.6, refreshing the browser will cause the code to enter a (compile, fail, repeat) loop. It attempts to compile four times before finally returning to the browser after the last failure. I thought it was Chrome being clever and re-requesting the page, but I've reproduced it with curl as well. 

### Play Version

2.6.X (tested with 2.6.3)

### API

Scala (maybe both)

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

MacOS Sierra

### Expected Behavior

1. Introduce compile error in project.
2. Start the app with `run`.
3. Refresh the browser or curl url.
4. Play will attempt to compile once, fail, and return a "Compilation failed" page

### Actual Behavior

1. Introduce compile error in project.
2. Start the app with `run`.
3. Refresh the browser or curl url.
4. Play will attempt to compile *four* times, before returning a "Compilation failed" page

### Reproducible Test Case

1. `sbt new playframework/play-scala-seed.g8`
2. Introduce compile error in project (add a few random characters to the controller).
2. Start the app with `run`.
3. Refresh the browser or curl url.
4. Play will attempt to compile four times.

```
[info] Compiling 1 Scala source to /Users/kyle/Temp/xxx/target/scala-2.12/classes...
[error] /Users/kyle/Temp/xxx/app/controllers/HomeController.scala:22: value xxx is not a member of play.api.mvc.Result
[error]     Ok(views.html.index())xxx
[error]                           ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[info] Compiling 1 Scala source to /Users/kyle/Temp/xxx/target/scala-2.12/classes...
[error] /Users/kyle/Temp/xxx/app/controllers/HomeController.scala:22: value xxx is not a member of play.api.mvc.Result
[error]     Ok(views.html.index())xxx
[error]                           ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[error] application -

! @7559l0cdj - Internal server error, for (GET) [/] ->

play.sbt.PlayExceptions$CompilationException: Compilation error[value xxx is not a member of play.api.mvc.Result]
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27)
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27)
	at scala.Option.map(Option.scala:145)
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:49)
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:44)
	at scala.Option.map(Option.scala:145)
	at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:44)
	at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:40)
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17)
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17)
[info] Compiling 1 Scala source to /Users/kyle/Temp/xxx/target/scala-2.12/classes...
[error] /Users/kyle/Temp/xxx/app/controllers/HomeController.scala:22: value xxx is not a member of play.api.mvc.Result
[error]     Ok(views.html.index())xxx
[error]                           ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[info] Compiling 1 Scala source to /Users/kyle/Temp/xxx/target/scala-2.12/classes...
[error] /Users/kyle/Temp/xxx/app/controllers/HomeController.scala:22: value xxx is not a member of play.api.mvc.Result
[error]     Ok(views.html.index())xxx
[error]                           ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
```

### PR DESCRIPTION
**Pull request by Enalmada**
Fixes #7753

## Purpose

Rolls back #8213, the removal of shortcut icon which when removed, chrome tries to hit server for default /favicon.ico causing the server to recompile everything again.

## Background Context

#8213 was intended to solve #7105 but went to far when removing the favicon from development templates

## References

Are there any relevant issues / PRs / mailing lists discussions?
#7753, #8213, #7105

### CODE REVIEW

File: framework/src/play/src/main/scala/views/defaultpages/devError.scala.html [hunk 1]
```diff
@@ -7,6 +7,7 @@
 <html lang="en">
     <head>
         <title>@error.title</title>
+        <link rel="shortcut icon" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAlFJREFUeNqUU8tOFEEUPVVdNV3dPe8xYRBnjGhmBgKjKzCIiQvBoIaNbly5Z+PSv3Aj7DSiP2B0rwkLGVdGgxITSCRIJGSMEQWZR3eVt5sEFBgTb/dN1yvnnHtPNTPG4PqdHgCMXnPRSZrpSuH8vUJu4DE4rYHDGAZDX62BZttHqTiIayM3gGiXQsgYLEvATaqxU+dy1U13YXapXptpNHY8iwn8KyIAzm1KBdtRZWErpI5lEWTXp5Z/vHpZ3/wyKKwYGGOdAYwR0EZwoezTYApBEIObyELl/aE1/83cp40Pt5mxqCKrE4Ck+mVWKKcI5tA8BLEhRBKJLjez6a7MLq7XZtp+yyOawwCBtkiBVZDKzRk4NN7NQBMYPHiZDFhXY+p9ff7F961vVcnl4R5I2ykJ5XFN7Ab7Gc61VoipNBKF+PDyztu5lfrSLT/wIwCxq0CAGtXHZTzqR2jtwQiXONma6hHpj9sLT7YaPxfTXuZdBGA02Wi7FS48YiTfj+i2NhqtdhP5RC8mh2/Op7y0v6eAcWVLFT8D7kWX5S9mepp+C450MV6aWL1cGnvkxbwHtLW2B9AOkLeUd9KEDuh9fl/7CEj7YH5g+3r/lWfF9In7tPz6T4IIwBJOr1SJyIGQMZQbsh5P9uBq5VJtqHh2mo49pdw5WFoEwKWqWHacaWOjQXWGcifKo6vj5RGS6zykI587XeUIQDqJSmAp+lE4qt19W5P9o8+Lma5DcjsC8JiT607lMVkdqQ0Vyh3lHhmh52tfNy78ajXv0rgYzv8nfwswANuk+7sD/Q0aAAAAAElFTkSuQmCC">
```
Comment (marcospereira) [inline framework/src/play/src/main/scala/views/defaultpages/devError.scala.html]: Re-add this on `./framework/src/play/src/main/scala/views/defaultpages/devNotFound.scala.html` too?

Comment (Enalmada) [reply framework/src/play/src/main/scala/views/defaultpages/devError.scala.html]: Ya, I should have.  Done!

**Comment by marcospereira** [comment]
2.6.x: 2528715c5e8d6b33ead5952f3986010b2ea77fa8
