### PR TITLE
Avoid multiple calls to ApplicationProvider#get for a single request

### LINKED ISSUE #7753: Compile error triggers multiple compilations
Normally, when I screw up my code and "run" my app, refreshing the web browser causes play to compile, fail, and return a "Compilation failed" page. Since upgrading to 2.6, refreshing the browser will cause the code to enter a (compile, fail, repeat) loop. It attempts to compile four times before finally returning to the browser after the last failure. I thought it was Chrome being clever and re-requesting the page, but I've reproduced it with curl as well. 

### Play Version

2.6.X (tested with 2.6.3)

### API

Scala (maybe both)

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

MacOS Sierra

### Expected Behavior

1. Introduce compile error in project.
2. Start the app with `run`.
3. Refresh the browser or curl url.
4. Play will attempt to compile once, fail, and return a "Compilation failed" page

### Actual Behavior

1. Introduce compile error in project.
2. Start the app with `run`.
3. Refresh the browser or curl url.
4. Play will attempt to compile *four* times, before returning a "Compilation failed" page

### Reproducible Test Case

1. `sbt new playframework/play-scala-seed.g8`
2. Introduce compile error in project (add a few random characters to the controller).
2. Start the app with `run`.
3. Refresh the browser or curl url.
4. Play will attempt to compile four times.

```
[info] Compiling 1 Scala source to /Users/kyle/Temp/xxx/target/scala-2.12/classes...
[error] /Users/kyle/Temp/xxx/app/controllers/HomeController.scala:22: value xxx is not a member of play.api.mvc.Result
[error]     Ok(views.html.index())xxx
[error]                           ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[info] Compiling 1 Scala source to /Users/kyle/Temp/xxx/target/scala-2.12/classes...
[error] /Users/kyle/Temp/xxx/app/controllers/HomeController.scala:22: value xxx is not a member of play.api.mvc.Result
[error]     Ok(views.html.index())xxx
[error]                           ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[error] application -

! @7559l0cdj - Internal server error, for (GET) [/] ->

play.sbt.PlayExceptions$CompilationException: Compilation error[value xxx is not a member of play.api.mvc.Result]
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27)
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27)
	at scala.Option.map(Option.scala:145)
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:49)
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:44)
	at scala.Option.map(Option.scala:145)
	at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:44)
	at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:40)
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17)
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17)
[info] Compiling 1 Scala source to /Users/kyle/Temp/xxx/target/scala-2.12/classes...
[error] /Users/kyle/Temp/xxx/app/controllers/HomeController.scala:22: value xxx is not a member of play.api.mvc.Result
[error]     Ok(views.html.index())xxx
[error]                           ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[info] Compiling 1 Scala source to /Users/kyle/Temp/xxx/target/scala-2.12/classes...
[error] /Users/kyle/Temp/xxx/app/controllers/HomeController.scala:22: value xxx is not a member of play.api.mvc.Result
[error]     Ok(views.html.index())xxx
[error]                           ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
```

### PR DESCRIPTION
**Pull request by gmethvin**
As far as I can tell, `ApplicationProvider#get` is not meant to be called multiple times for the same request. It looks like that was the case previously, but in 2.6.x we've added some caching based on the `Try[Application]` instance and are calling the `ApplicationProvider` to get the current instance each time. The current dev mode reload logic forces a reload next time (`forceReloadNextTime = true`) when compilation fails, so if `get` is called more than once for a single request, that causes multiple compilations per request.

My solution here proposes to get the `Try[Application]` once and pass that instance around for the handling of the request.

Fixes #7753

### CODE REVIEW

**Comment by richdougherty** [comment]
Also fixes #7650 - thanks! I can review this tomorrow if you like.

**Comment by gmethvin** [comment]
👍 A review would be great. I'm not totally happy with the way the code is structured now so I wonder if you have ideas on how to do it more elegantly.

**Comment by mkurz** [comment]
Regarding [the comment above](https://github.com/playframework/playframework/pull/8166#issuecomment-358252051):
> Also fixes #7650 - thanks! I can review this tomorrow if you like.

I guess we can close #7650 now.
