### PR TITLE
[2.5.x] Add additional @Targets to constraints

### PR DESCRIPTION
**Pull request by mkurz**
Backports #7032

### CODE REVIEW

**Comment by mkurz** [comment]
The test [fails](https://travis-ci.org/playframework/playframework/jobs/209351660#L1234-L1240) because Scala 2.11.8 doesn't recognize Java type-annotations ([Scala bug](https://issues.scala-lang.org/browse/SI-9853)):

```
[error] /home/travis/build/playframework/playframework/framework/src/play-java/src/test/java/play/data/ListForm.java:15: illegal start of type
[error]     private List<@Constraints.Min(0) Integer> values;
[error]                  ^
[error] /home/travis/build/playframework/playframework/framework/src/play-java/src/test/java/play/data/ListForm.java:15: `>' expected but `;' found.
[error]     private List<@Constraints.Min(0) Integer> values;
[error]                                                     ^
[error] two errors found
```

However the issue doesn't occur with Scala 2.12.1 anymore (the scala bug report can actually be closed). That's why in the master branch the test passed.

@marcospereira What should we do? IMHO we could just remove the test for the 2.5.x branch. Using type-annotations in a 2.5 play-java project still works for us anyway.

**Comment by marcospereira** [comment]
@mkurz can't we have a test written in Java instead? If this is too much inconvenience, then I agree that we can remove the test here.

**Comment by mkurz** [comment]
@marcospereira Thats what I am doing right now :smile:

**Comment by mkurz** [comment]
@marcospereira OK this won't work. The `ListForm.java` wont compile no matter what. (Even when not having a applicable test).

**Comment by mkurz** [comment]
Wait... Seems like this was a caching issue

**Comment by mkurz** [comment]
I can't get it working, it just doesn't compile. I don't want to waste more time, I will just remove the test.

**Comment by mkurz** [comment]
@marcospereira Build is green, test removed.

**Comment by mkurz** [comment]
Because this kept me occupied I again tried to add a test. And here is the thing:

In a pure Java only project (where not even a single `.scala` file exists / also I am talking about plain `sbt` projects) a Java source file with an annotation on a type parameter like [this](https://github.com/playframework/playframework/blob/2.6.0-M2/framework/src/play-java-forms/src/test/java/play/data/ListForm.java#L15) would compile successfully. I am not fully aware how `sbt`/`scala` compilation works, but it seems when there is no scala file present only `javac` will be used. But as soon as you add one (dummy) scala file the scala compiler kicks in and you won't be able to compile your project anymore because you run into [SI-9853](https://issues.scala-lang.org/browse/SI-9853).
So to add a test which compiles we would have to add a java-only sub-project (in the `framework/src` folder) which would basically only contain the Java test source file (`ListForm.java`) and an applicable test - and no scala file. I think this is a bit overkill. But not only would it be an overkill it wouldn't really make much sense. Yes, it would compile and the test would run. However a requirement for a Play (Java) user to use such an annotation on a constraint type argument in a Play 2.5 project would be to not use any scala files(s) at all in their PlayJava projects - otherwise they would also run into the scala bug.
**Worst case:** We merge this PR into the 2.5.x branch, people upgrade, start using things like `List<@Min(0) Integer>` for validation and it would compile and work (because they have java only projects). For some reason however they add a scala file later on - boom :boom:, the app doesn't even compile anymore.

Given that with Scala 2.11 this isn't working stable I think best thing to do is to not backport this at all.

PS: You may be interested that during my research I also tried to just re-write the `ListForm` class in scala, thinking this might compile, it turned out scala won't even translate annotations on type arguments defined in Scala files into bytecode yet. See [SI-9883](https://issues.scala-lang.org/browse/SI-9883).

**Comment by mkurz** [comment]
@marcospereira If you think we still should backport this or have an idea on how to workaround the scala 2.11 bug, feel free to re-open this PR.

**Comment by marcospereira** [comment]
@mkurz, actually, if this is not working with Scala 2.11, I wonder if we have a stable version of this change in master branch too. That is because master cross builds for Scala 2.11 and Scala 2.12.

So, will projects using Play 2.6.0 **and** Scala 2.11 work as expected?

Specifically about the backport to 2.5.x, while it is desirable it is not required. 2.5.x branch focus is stability and if we need to add more changes to accommodate this change, I would vote against it.

**Comment by marcospereira** [comment]
@mkurz so, master branch is broken when building against Scala 2.11 too. You can confirm that with:

```bash
cd framework
sbt ++2.11.8 Play-Java-Forms/test
```

Which results in the following error:

```
[error] /Users/marcospereira/Lightbend/playframework/framework/src/play-java-forms/src/test/java/play/data/ListForm.java:15: illegal start of type
[error]     private List<@Constraints.Min(0) Integer> values;
[error]                  ^
[error] /Users/marcospereira/Lightbend/playframework/framework/src/play-java-forms/src/test/java/play/data/ListForm.java:15: `>' expected but `;' found.
[error]     private List<@Constraints.Min(0) Integer> values;
[error]                                                     ^
[error] two errors found
[error] (Play-Java-Forms/test:compileIncremental) Compilation failed
[error] Total time: 215 s, completed Mar 13, 2017 6:18:13 PM
```

**Comment by mkurz** [comment]
> So, will projects using Play 2.6.0 and Scala 2.11 work as expected?

Projects using Play 2.6.0 and Scala 2.11 using annotations on type parameters like `List<@Constraints.Min(0) Integer>` will compile as long as you do not add any **scala** file to a play-**java** project. (Because, as I mentioned above, I assume `sbt` will not use `scalac` but only `javac` when no scala files exists in a project - but I don't know if this is specified somewhere.)

[SI-9853](https://issues.scala-lang.org/browse/SI-9853) has now been officially been marked as resolved for Scala 2.12.
So Projects using Play 2.6.0 and Scala 2.12 will **always work**.

What do you think about adding an example like [`ListForm.java`](https://github.com/playframework/playframework/blob/master/framework/src/play-java-forms/src/test/java/play/data/ListForm.java#L12-L24) to the [validation documentation](https://www.playframework.com/documentation/2.6.x/JavaForms#Defining-constraints) but explicitly mentionioned this is only supported when using Scala 2.12?

**Comment by wsargent** [comment]
according to @dwijnand we might be able to workaround the issue by changing the compileOrder to `JavaThenScala`

**Comment by mkurz** [comment]
@wsargent See #7079

**Comment by mkurz** [comment]
We could now successful backport this by applying the same fix like #7079 in this PR. Will have a look later.
