### ISSUE TITLE
Play 2.7.0-M3 doesn't run annotation processors

### ISSUE THREAD

**Issue by eximius313** [playframework/playframework#8603]
### Play Version (2.5.x / etc)
2.7-M3

### API (Scala / Java / Neither / Both)
Both

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Windows 7

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
```
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
```

### Library Dependencies
N/A

### Expected Behavior
Annotation processors are fired

### Actual Behavior
When I change verion of Play in plugins.sbt and run `sbt clean compile` with `2.6.18` everything compiles. When I change version to `2.7.0-M3` and run `sbt clean compile` compilation fails with:
```
[error] C:\workspaces\project\repository\CompanyRepository.java:11:1: cannot find symbol
[error]   symbol:   class Company_
[error]   location: package domain
[error] import domain.Company_;
[error] C:\workspaces\project\repository\CompanyRepository.java:12:1: cannot find symbol
[error]   symbol:   class User_
[error]   location: package domain
[error] import domain.User_;
```
which are normally generated by Hibernate Metamodel Generator.
Moreover, there are errors:
```
[error] C:\workspaces\project\forms\MyForm.java:20:1: cannot find symbol
[error]   symbol:   variable FIELD_EMAIL
[error]   location: class project.forms.MyForm
```
So Lombok's `@FieldNameConstants` is also not fired

When I get bact to `2.6.18` everything compiles again.

`SBT` version in both configurations is `1.1.6`

**Comment by marcospereira** [comment]
Thanks for reporting, @eximius313.

Do you mind creating a project that reproduces the problem? I think it is worth checking which how Hibernate dependencies are changing when updating to M3.

Best.

**Comment by eximius313** [comment]
Ok, so I reproduced problem with Metamodel Generator: [play-annotation-processor-bug.zip](https://github.com/playframework/playframework/files/2372474/play-annotation-processor-bug.zip)
In my project I also observe problems with Lombok, but I couldn't reproduce that here. 
Nevertheless, I think they are related, so if you fix this bug, I'll check if Lombok works fine

**Comment by dwijnand** [comment]
I ran it, and verified it indeed works with 2.6 and fails with 2.7. How bizarre!

**Comment by marcospereira** [comment]
Hi @eximius313,

This was a problem with `hibernate-jpamodelgen`. I've noticed that it was generating the following code when using version `5.3.12.Final`:

```java
package model;

import (@javax.validation.constraints.NotNull :: byte);
import java.time.ZonedDateTime;
import javax.annotation.Generated;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@Generated(value = "org.hibernate.jpamodelgen.JPAMetaModelEntityProcessor")
@StaticMetamodel(MyEntity.class)
public abstract class MyEntity_ {

	public static volatile SingularAttribute<MyEntity, NotNull :: byte)[]> data;
	public static volatile SingularAttribute<MyEntity, ZonedDateTime> created;
	public static volatile SingularAttribute<MyEntity, Long> id;

}
```
The code above is not valid Java code as you can see. Updating `hibernate-jpamodelgen` to the [latest version](https://mvnrepository.com/artifact/org.hibernate/hibernate-jpamodelgen/5.3.6.Final) (`5.3..6.Final`) solved the problem. There is also [HHH-12612](https://hibernate.atlassian.net/browse/HHH-12612) with a discussion and claiming that it is also fixed for version `5.2.18`, but apparently this was not released yet.

But why was it working for 2.6.x?

Probably due to better compatibility between `hibernate-jpamodelgen` and `hibernate-validator` version used by Play 2.6.x ( `5.4.1.Final`). For Play 2.7.0-M3 we are using `hibernate-validator` `6.0.12.Final`. If we force `5.4.1.Final` on your reproducer **without** changing `hibernate-jpamodelgen` it also works:

```scala
dependencyOverrides ++= Seq(
  "org.hibernate" % "hibernate-validator" % "5.4.1.Final"
)
```

Of course, this is not recommended. So better to go with `hibernate-jpamodelgen` update.

Given all that, I'm closing this.

**Comment by eximius313** [comment]
I think, that this is good to note in Migration Guide

**Comment by marcospereira** [comment]
Reopening so that we can close after adding the details to our migration guide.

**Comment by eximius313** [comment]
@marcospereira I have exactly the same problem now with newest Mapstruct (1.3.0.Beta2).
* Play 2.6 + 1.2.0.Final = work fine
* Play 2.6 + Mapstruct 1.3.0.Beta2 = work fine
* Play 2.7 + 1.2.0.Final = work fine
* Play 2.7 + Mapstruct 1.3.0.Beta2 = error:
```
[error] C:\workspaces\project\repository\CompanyRepository.java:11:1: cannot find symbol
[error]   symbol:   class Company_
[error]   location: package domain
[error] import domain.Company_;
[error] C:\workspaces\project\repository\CompanyRepository.java:12:1: cannot find symbol
[error]   symbol:   class User_
[error]   location: package domain
[error] import domain.User_;
```
