### ISSUE TITLE
Reverse routing and nested package

### ISSUE THREAD

**Issue by rlavolee** [playframework/playframework#4963]
Hello,

Firstly thanks for your great framework.

I stumbled on a strange behaviour of the reverse routing feature while working with Play 2.4.2. You can find the simple case scenario in this github [repository](https://github.com/rlavolee/ReverseRouting/tree/develop).

Issue
--------

The `play-routes-compiler` can't generate the reverseGrade class in the ReverseRoute.scala file and consequently the compiler throws the following error. The only wild thing I made is create two controllers (Grade and Rank) inside a sub-package (studies) of the controller package and create nested route files. 

```
[error] /ReverseRouting/app/controllers/studies/Grade.scala:23: value Grade is not a member of object controllers.studies.routes
[error]     Future.successful(Redirect(routes.Grade.get("1"), CREATED))
[error]                                       ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
```

Setup
--------

Clone the repository and compile it. You will find it [here](https://github.com/rlavolee/ReverseRouting/tree/develop).

Requirements:

* Play 2.4.2
* SBT 0.13.8
* Scala 2.11.6
* Java version "1.8.0_51"

Wild Guess
--------

For now I'm not sure where this issue comes from. I might be the origin of it or might be the `play-routes-compiler` which can't handle multiple controller classes inside nested package.

Thanks again for your work and the time you take to read me. Moreover if I'm the cause of this error I'll be deeply sorry.

**Comment by marcospereira** [comment]
Hello @rlavolee, thanks for you gentle comments.

Do you mind discuss that first on the [user mailing list](https://groups.google.com/forum/m/#!forum/play-framework)? If we confirm that there is an error with Play, than we can open an issue.

Anyway, maybe this section of docs could help you:

https://www.playframework.com/documentation/2.4.x/SBTSubProjects#Splitting-your-web-application-into-several-parts

**Comment by rlavolee** [comment]
For the record, I opened a discussion on the user mailing list as you suggest. 

Moreover I understand the way to split the project but that's still a strange behavior from the play-routes-compiler.

**Comment by jroper** [comment]
It's strange until you understand how routes compilation works.  Read https://github.com/playframework/playframework/issues/4638#issuecomment-110770978 for more details.

**Comment by rlavolee** [comment]
Thanks for the explanation. I didn't know about this constraint.
