### ISSUE TITLE
Compile error triggers multiple compilations

### ISSUE THREAD

**Issue by KyleU** [playframework/playframework#7753]
Normally, when I screw up my code and "run" my app, refreshing the web browser causes play to compile, fail, and return a "Compilation failed" page. Since upgrading to 2.6, refreshing the browser will cause the code to enter a (compile, fail, repeat) loop. It attempts to compile four times before finally returning to the browser after the last failure. I thought it was Chrome being clever and re-requesting the page, but I've reproduced it with curl as well. 

### Play Version

2.6.X (tested with 2.6.3)

### API

Scala (maybe both)

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

MacOS Sierra

### Expected Behavior

1. Introduce compile error in project.
2. Start the app with `run`.
3. Refresh the browser or curl url.
4. Play will attempt to compile once, fail, and return a "Compilation failed" page

### Actual Behavior

1. Introduce compile error in project.
2. Start the app with `run`.
3. Refresh the browser or curl url.
4. Play will attempt to compile *four* times, before returning a "Compilation failed" page

### Reproducible Test Case

1. `sbt new playframework/play-scala-seed.g8`
2. Introduce compile error in project (add a few random characters to the controller).
2. Start the app with `run`.
3. Refresh the browser or curl url.
4. Play will attempt to compile four times.

```
[info] Compiling 1 Scala source to /Users/kyle/Temp/xxx/target/scala-2.12/classes...
[error] /Users/kyle/Temp/xxx/app/controllers/HomeController.scala:22: value xxx is not a member of play.api.mvc.Result
[error]     Ok(views.html.index())xxx
[error]                           ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[info] Compiling 1 Scala source to /Users/kyle/Temp/xxx/target/scala-2.12/classes...
[error] /Users/kyle/Temp/xxx/app/controllers/HomeController.scala:22: value xxx is not a member of play.api.mvc.Result
[error]     Ok(views.html.index())xxx
[error]                           ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[error] application -

! @7559l0cdj - Internal server error, for (GET) [/] ->

play.sbt.PlayExceptions$CompilationException: Compilation error[value xxx is not a member of play.api.mvc.Result]
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27)
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27)
	at scala.Option.map(Option.scala:145)
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:49)
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:44)
	at scala.Option.map(Option.scala:145)
	at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:44)
	at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:40)
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17)
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17)
[info] Compiling 1 Scala source to /Users/kyle/Temp/xxx/target/scala-2.12/classes...
[error] /Users/kyle/Temp/xxx/app/controllers/HomeController.scala:22: value xxx is not a member of play.api.mvc.Result
[error]     Ok(views.html.index())xxx
[error]                           ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[info] Compiling 1 Scala source to /Users/kyle/Temp/xxx/target/scala-2.12/classes...
[error] /Users/kyle/Temp/xxx/app/controllers/HomeController.scala:22: value xxx is not a member of play.api.mvc.Result
[error]     Ok(views.html.index())xxx
[error]                           ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
```

**Comment by richdougherty** [comment]
Thanks a lot for the report. I'm not sure why we didn't notice this earlier!

I have reproduced now too. I'm on Mac OS 10.12.6 (Sierra) running Java 1.8.0_60-b27. I have reproduced on 2.6.0-2.6.3.

Script 1:
1. remove `target` and `project/target` directories
2. introduce error into application source
3. `sbt`
4. `run`
5. request page in browswer
6. see 3-4 compile errors.

Script 2:
1. remove `target` and `project/target` directories
2. fix application source so it compiles, 
3. `sbt`
4. `run`
5. request page in browswer
6. compile happens (once), see page in browser
7. introduce error into application source
8. request page in browswer
9. usually see 1 compile error only, but sometimes more

**Comment by hepin1989** [comment]
I was thought that is triggered by the `sbt-scalariform` plugin,seems not.

**Comment by hepin1989** [comment]
![image](https://user-images.githubusercontent.com/501740/29915324-1babc15a-8e6e-11e7-8c0d-7f48cc671652.png)

it's very annoying，as it is

**Comment by richdougherty** [comment]
> I was thought that is triggered by the sbt-scalariform plugin,seems not.

I'm assuming there's a race condition in our file watching/compiling code.

> it's very annoying，as it is

Yes!

**Comment by hepin1989** [comment]
```
                                     ^
[info] Set current project to beehive-facade (in build file:/C:/Users/kerr/IdeaProjects/BeehiveFacade/)
[beehive-facade] $ run

--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Enter to stop and go back to the console...)

[info] Compiling 6 Scala sources and 1 Java source to C:\Users\kerr\IdeaProjects\BeehiveFacade\target\scala-2.12\classes...
[error] IO error while decoding C:\Users\kerr\IdeaProjects\BeehiveFacade\target\scala-2.12\routes\main\router\Routes.scala with UTF-8
[error] Please try specifying another one using the -encoding option
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[info] Compiling 6 Scala sources and 1 Java source to C:\Users\kerr\IdeaProjects\BeehiveFacade\target\scala-2.12\classes...
[error] IO error while decoding C:\Users\kerr\IdeaProjects\BeehiveFacade\target\scala-2.12\routes\main\router\Routes.scala with UTF-8
[error] Please try specifying another one using the -encoding option
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[info] Compiling 6 Scala sources and 1 Java source to C:\Users\kerr\IdeaProjects\BeehiveFacade\target\scala-2.12\classes...
[error] IO error while decoding C:\Users\kerr\IdeaProjects\BeehiveFacade\target\scala-2.12\routes\main\router\Routes.scala with UTF-8
[error] Please try specifying another one using the -encoding option
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[error] application -

! @75b532609 - Internal server error, for (GET) [/robots.txt] ->

play.sbt.PlayExceptions$CompilationException: Compilation error[IO error while decoding C:\Users\kerr\IdeaProjects\BeehiveFacade\target\sca
la-2.12\routes\main\router\Routes.scala with UTF-8
Please try specifying another one using the -encoding option]
        at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27)
        at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27)
        at scala.Option.map(Option.scala:145)
        at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:49)
        at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:44)
        at scala.Option.map(Option.scala:145)
        at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:44)
        at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:40)
        at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17)
        at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17)
[info] Compiling 6 Scala sources and 1 Java source to C:\Users\kerr\IdeaProjects\BeehiveFacade\target\scala-2.12\classes...
[error] IO error while decoding C:\Users\kerr\IdeaProjects\BeehiveFacade\target\scala-2.12\routes\main\router\Routes.scala with UTF-8
[error] Please try specifying another one using the -encoding option
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[error] application -

! @75b53290k - Internal server error, for (GET) [/beehive/explorer] ->

play.sbt.PlayExceptions$CompilationException: Compilation error[IO error while decoding C:\Users\kerr\IdeaProjects\BeehiveFacade\target\sca
la-2.12\routes\main\router\Routes.scala with UTF-8
Please try specifying another one using the -encoding option]
        at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27)
        at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27)
        at scala.Option.map(Option.scala:145)
        at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:49)
        at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:44)
        at scala.Option.map(Option.scala:145)
        at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:44)
        at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:40)
        at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17)
        at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17)
[info] Compiling 6 Scala sources and 1 Java source to C:\Users\kerr\IdeaProjects\BeehiveFacade\target\scala-2.12\classes...
[error] IO error while decoding C:\Users\kerr\IdeaProjects\BeehiveFacade\target\scala-2.12\routes\main\router\Routes.scala with UTF-8
[error] Please try specifying another one using the -encoding option
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[info] Compiling 6 Scala sources and 1 Java source to C:\Users\kerr\IdeaProjects\BeehiveFacade\target\scala-2.12\classes...
[INFO] [09/15/2017 00:43:19.868] [Thread-4] [CoordinatedShutdown(akka://play-dev-mode)] Starting coordinated shutdown from JVM shutdown hoo
k
[error] IO error while decoding C:\Users\kerr\IdeaProjects\BeehiveFacade\target\scala-2.12\routes\main\router\Routes.scala with UTF-8
[error] Please try specifying another one using the -encoding option
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[info] Compiling 6 Scala sources and 1 Java source to C:\Users\kerr\IdeaProjects\BeehiveFacade\target\scala-2.12\classes...
[error] IO error while decoding C:\Users\kerr\IdeaProjects\BeehiveFacade\target\scala-2.12\routes\main\router\Routes.scala with UTF-8
[error] Please try specifying another one using the -encoding option
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[info] Compiling 6 Scala sources and 1 Java source to C:\Users\kerr\IdeaProjects\BeehiveFacade\target\scala-2.12\classes...
[error] IO error while decoding C:\Users\kerr\IdeaProjects\BeehiveFacade\target\scala-2.12\routes\main\router\Routes.scala with UTF-8
[error] Please try specifying another one using the -encoding option
[error] one error found
[error] (compile:compileIncremental) Compilation failed
终止批处理操作吗(Y/N)? ^C

```

**Comment by sergeych** [comment]
It is very annoying. Why do you keep postponing it?

**Comment by shkhln** [comment]
Well, it looks like Play indeed [triggers](https://github.com/playframework/playframework/blob/c6d639d709b85c2802b135156ea9aed425494815/framework/src/play-server/src/main/scala/play/core/server/DevServerStart.scala#L123) compilation [4 times per request](https://gist.github.com/shkhln/9781b9e062bbf791b6f2c162f334b24c).

**Comment by shkhln** [comment]
And then it sets [`forceReloadNextTime = true`](https://github.com/playframework/playframework/blob/b5a88b3af2b806d519cf4d7afad704f847f4899d/framework/src/run-support/src/main/scala/play/runsupport/Reloader.scala#L423) on on each compilation failure.

**Comment by sergeych** [comment]
Yes, I've seen it - that it reloads multiple times, it's very annoying itself, and with errors - it's a real pain. Most often I can figure out the error before play stops flooding logs with repeating error messages ;) Multiple reloading therefore makes play hardly usable in professional development, as it slows it down and reduces developer hour outcome, what is a critical flaw.

**Comment by nemoo** [comment]
This issue renders recent performance improvements of the scala platfortform pretty much irrelevant. This increases the compile time in case of an error by 300% (4 times). And it does so in a very annoying way because as son as  your eyes fixate on an error message, it recompiles again and your eyes lose focus on the error. Given that this produces an extremely bad user experience when working with play framework, please consider increasing the priority of this issue.

**Comment by gavares** [comment]
I agree with @nemoo. Postponing a fix for this to Play 2.7 seems like the wrong prioritization for this issue.

This bug has real and tangible effect on development speed. Considering that scala code compilation is not particularly fast to begin with, paying to compile 4 times per change when there is an error can result in very long edit-compile cycles for even the smallest of changes. 

Surprising to see this bug still open after nearly 6 months and, given that 2.7 has no set due date in the milestone, there is still no fix in sight.

**Comment by richdougherty** [comment]
I'll raise this issue at our next team meeting. I've put a *help wanted* tag on this just in case someone else wants to contribute in the meantime.

**Comment by sergeych** [comment]
Hope you'll fix it. Very annoying, together with meta memory leak I'd
consider it as the critical issue.

пн, 15 янв. 2018 г., 2:42 Rich Dougherty <notifications@github.com>:

**Comment by sergeych** [comment]
Great why don't you include this fix into closest release? We're waiting for it...

**Comment by shkhln** [comment]
You are missing out. The fix has been backported to 2.6.x branch (https://github.com/playframework/playframework/pull/8169) and is available since 2.6.12.

**Comment by sergeych** [comment]
great! thanks!

**Comment by easel** [comment]
I'm still seeing the "compiles 4x" behavior using play 2.6.13. Can anyone verify that the fix in 2.6.12+ is working?

**Comment by shkhln** [comment]
> I'm still seeing the "compiles 4x" behavior using play 2.6.13.

Four times exactly or just multiple times?

> Can anyone verify that the fix in 2.6.12+ is working?

Works for me.

**Comment by nemoo** [comment]
I just tested using 2.6.12 and I see compile errors at least twice, sometimes three times after a single code change.

**Comment by shkhln** [comment]
Well, I truly hate pointing it out, but it's pretty simple issue to [debug](https://gist.github.com/shkhln/9781b9e062bbf791b6f2c162f334b24c#file-diff). Anyone?

**Comment by Enalmada** [comment]
Perhaps it is something specific to windows 10...is anyone seeing this error not on windows 10?

@shkhln Are you asking for someone with the problem to create a similar gist of a Thread.dumpStack() in DevServerStart while the redundant recompiles are going?  I have no docs and modules where I can but I have no play debug experience so I am hoping that someone that does with Windows 10 around can step up.  But this is such I high severity issue I will do whatever I can to follow specific directions to get my env up to a place I can generate logs that could help...or I can let someone who knows what they are doing remote connect.   I appreciate everyone that has contributed to this as the multiple recompile really kills productivity.

**Comment by shkhln** [comment]
> Are you asking for someone with the problem to create a similar gist of a Thread.dumpStack() in DevServerStart while the redundant recompiles are going?

Yes. It's also possible to use [btrace](https://github.com/btraceio/btrace) to obtain that information if you don't want to recompile Play.

**Comment by KyleU** [comment]
`2.6.12` fixed it for me, MacOS/GraalVM. I haven't seen the multiple compile issue since then, but can reproduce it by downgrading to `.11`.

**Comment by Enalmada** [comment]
btrace is an good suggestion and worth knowing about for future problems.  If anyone ever tries it in the future be sure to look in the samples directory for script examples.

I got play stack trace going as requested after [some windows difficulty](https://github.com/playframework/playframework/issues/8449) hacked around to work.  Looking closely at the output I now notice that every time I refresh the browser I have 3 duplicate errors but the actual reason is that the browser is making three calls per refresh:
1)  /service-worker.js
2)  /current-browser-url
3)  /favicon.ico

All I would have expected is my current-browser-url.  I am not sure why the service-worker.js script feels the need to hit the server on an error page and I will look into that.  The favicon.ico is apparently a chrome issue and the solution seems to be to put a [link tag in the devError page](https://stackoverflow.com/a/38917888/1502448) head so chrome doesn't try and hit the server for the default one causing another recompile error in the console.

**Comment by easel** [comment]
@Enalmada that's a good catch, I'm sure some of my duplicate refreshes are due to exactly that. All that being said, the dev server really ought to be catching all inbound requests and attaching them to a single recompile, not kicking off new ones for every inbound request.

**Comment by shkhln** [comment]
> /favicon.ico

That's funny, favicons were only recently [removed](https://github.com/playframework/playframework/pull/8213) to (partially) satisfy a pretty absurd set of [demands](https://github.com/playframework/playframework/issues/7105). Some people really should learn to say 'No' more often.

**Comment by Enalmada** [comment]
Doh.  Someone went overboard removing them from all templates...they should have only done the production templates to satisfy the demands.  The favicon should go back into devError.scala.html to avoid the additional recompile hit to all developers using chrome.

**Comment by Enalmada** [comment]
@easel Agreed.  Is there any chance of having play only do a recompile from an incoming request if anything has changed since the last recompile?
