### PR TITLE
Java 8 static method in interface does not compile in Play 2.4.0-RC5

### PR DESCRIPTION
**Pull request by marcospereira**
Given I have a static method in a Java interface

```java
public interface Java8Interface {
    static String foo() {
        return "foo";
    }
}
```

Then a Play 2.4.0-RC5 project fails to compile it

```
[error] /home/travis/build/schleichardt/play-2-4-java-8-compile-errors/app/demo/Java8Interface.java:4: `;' expected but `{' found.
[error]     static String foo() {
[error]                         ^
[error] one error found
[error] (root/compile:compileIncremental) Compilation failed
```

* test project to reproduce: https://github.com/schleichardt/play-2-4-java-8-compile-errors
* travis output for a plain sbt project which compiles the interface: https://travis-ci.org/schleichardt/play-2-4-java-8-compile-errors/builds/63322694#L786
    * see https://github.com/schleichardt/play-2-4-java-8-compile-errors/blob/master/build.sbt#L7
* travis output for failing compilation in play project: https://travis-ci.org/schleichardt/play-2-4-java-8-compile-errors/builds/63322694#L1301
* there is a related bug report in the mailing list https://groups.google.com/forum/#!topic/play-framework/JdyeQNycQPI

### CODE REVIEW

**Comment by marcospereira** [comment]
@play-pull-request-validator

**Comment by richdougherty** [comment]
We're getting a lot of resolution failures for this library at the moment:
```
sbt.ResolveException: unresolved dependency: com.typesafe.sbtrc#client-2-10;0.3.1: not found
```

**Comment by jroper** [comment]
Backported to 2.4.x: bbc2221
