### PR TITLE
Build and test docs in scala 2.13

### LINKED ISSUE #9367: Run documentation tests using Scala 2.13
To ensure all the code snippets in our docs also work correctly with Scala 2.13.

### PR DESCRIPTION
**Pull request by ignasi35**
Fixes #9367

Scala 2.13 is only used to `sbt test` (not validate, format, etc...)

### CODE REVIEW

**Comment by ignasi35** [comment]
this still fails on my machine with:


```
[error] /Users/ignasi/git/projects/lightbend/playframework/playframework/documentation/manual/working/scalaGuide/main/upload/code/ScalaFileUpload.scala:93:36: type HomeController is not a member of package play.api.controllers
[error]         testAction(new controllers.HomeController(controllerComponents).upload, request)
[error]                                    ^
[error] one error found
```

This looked like a regression to me: trying to locate [`controllers.HomeController`](https://github.com/playframework/playframework/blob/master/documentation/manual/working/scalaGuide/main/upload/code/ScalaFileUpload.scala#L116-L118) (same file, inner package). I'm probably missing a new feature in scala 2.13 that impacts this code.

/cc @dwijnand @SethTisue

**Comment by ignasi35** [comment]
The `new controllers.HomeController` compilation error seems to be a change in behavior on how scala `2.13` resolves imports.

The code can be simplified to:

```scala
package scalaguide.upload.fileupload {

	import controllers._ 
	// other imports 
	import play.api._
	
    class MyTest {
      // some stuff 
  	  new controllers.HomeController(..)
    }

	package controllers {
	   class HomeController()
    }
}
	
```

The issue is that `controllers` is ambiguous because there's a `play.api.controllers`  in scope too.

**Comment by dwijnand** [comment]
https://github.com/scala/scala/pull/6589 probably

**Comment by renatocaval** [comment]
This one is included (indirectly) on Milestone 2.8.0-M2.

Shall we just fix it as merge before cutting 2.8.0-M2?

**Comment by ignasi35** [comment]
This PR is currently broken due to API changes in `Ordering` and `Either`. See the sample below:

```
[error] /Users/ignasi/git/projects/lightbend/playframework/playframework/documentation/manual/working/scalaGuide/advanced/routing/code/scalaguide/binder/models/User.scala:30:44: method right in class Either is deprecated (since 2.13.0): Either is now right-biased, use methods directly on Either
[error]         id   <- intBinder.bind(key, value).right
[error]                                            ^
[error] 
...
/Users/ignasi/git/projects/lightbend/playframework/playframework/documentation/manual/working/scalaGuide/main/json/code/ScalaJsonHttpSpec.scala:164:70: object DeprecatedDoubleOrdering in object Ordering is deprecated (since 2.13.0): There are multiple ways to order Doubles (Ordering.Double.TotalOrdering, Ordering.Double.IeeeOrdering). Specify one by using a local import, assigning an implicit val, or passing it explicitly. See the documentation for details.
[error]           .and((JsPath \ "long").read[Double](min(-180.0).keepAnd(max(180.0))))
[error]                                                                      ^
[error] 7 errors found
```

The broken code are snippets displayed in the docs so extra hacks would leak to presented docs.

Also, to make the code above cross-compile in both `2.12` and `2.13` will require some hacking on the `documentation` build itself so maybe we can _just_ drop `2.12` for the docs execution and state all samples are scala `2.13` code? /cc @dwijnand @renatocaval @marcospereira

**Comment by dwijnand** [comment]
I think just drop fatal warnings instead.

File: documentation/build.sbt [hunk 1]
```diff
@@ -24,7 +24,7 @@ lazy val main = Project("Play-Documentation", file("."))
       "-parameters",
       "-Xlint:unchecked",
       "-Xlint:deprecation",
-      "-Werror"
+//      "-Werror"
```
Comment (dwijnand) [inline documentation/build.sbt]: More importantly drop the `-Xfatal-warnings` 7 lines above.

Comment (ignasi35) [reply documentation/build.sbt]: _gets ☕_

**Comment by ignasi35** [comment]
Meh, javac's `-Werror` must be disabled too because of deprecations in `scala.collection.JavaConverters`

**Comment by ignasi35** [comment]
This PR is currently blocked by what seems to be invalid sync in maven central. There are multiple artifact failures but the most recurring one is:

```
[warn] 	[FAILED     ] com.typesafe.play#twirl-api_2.12;1.5.0-M2!twirl-api_2.12.jar: The HTTP response code for https://repo1.maven.org/maven2/com/typesafe/play/twirl-api_2.12/1.5.0-M2/twirl-api_2.12-1.5.0-M2.jar did not indicate a success. See log for more detail. (108ms)
[warn] 	Detected merged artifact: [FAILED     ] com.typesafe.play#twirl-api_2.12;1.5.0-M2!twirl-api_2.12.jar: The HTTP response code for https://repo1.maven.org/maven2/com/typesafe/play/twirl-api_2.12/1.5.0-M2/twirl-api_2.12-1.5.0-M2.jar did not indicate a success. See log for more detail. (108ms).
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/play/twirl-api_2.12/1.5.0-M2/twirl-api_2.12-1.5.0-M2.jar
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::              FAILED DOWNLOADS            ::
[warn] 	:: ^ see resolution messages for details  ^ ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.typesafe.play#twirl-api_2.12;1.5.0-M2!twirl-api_2.12.jar
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[error] sbt.librarymanagement.ResolveException: download failed: com.typesafe.play#twirl-api_2.12;1.5.0-M2!twirl-api_2.12.jar
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:332)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:239)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
```

**Comment by ignasi35** [comment]
Just [wow](https://travis-ci.com/playframework/playframework/jobs/211064040#L734):

```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::              FAILED DOWNLOADS            ::
[warn] 	:: ^ see resolution messages for details  ^ ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.ning#async-http-client;1.9.11!async-http-client.jar
[warn] 	:: org.json4s#json4s-scalap_2.12;3.4.2!json4s-scalap_2.12.jar
[warn] 	:: org.json4s#json4s-native_2.12;3.4.2!json4s-native_2.12.jar
[warn] 	:: org.slf4j#slf4j-nop;1.7.7!slf4j-nop.jar
[warn] 	:: com.google.code.gson#gson;2.2.2!gson.jar
[warn] 	:: org.whitesource#wss-agent-report;2.7.9!wss-agent-report.jar
[warn] 	:: commons-collections#commons-collections;3.2.1!commons-collections.jar
[warn] 	:: org.scalameta#sbt-scalafmt;2.0.1!sbt-scalafmt.jar
[warn] 	:: org.webjars#webjars-locator-core;0.37!webjars-locator-core.jar
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

File: documentation/build.sbt [hunk 2]
```diff
@@ -70,7 +70,7 @@ lazy val main = Project("Play-Documentation", file("."))
     // Don't include sbt files in the resources
     excludeFilter in (Test, unmanagedResources) := (excludeFilter in (Test, unmanagedResources)).value || "*.sbt",
     crossScalaVersions := Seq("2.13.0", "2.12.8"),
-    scalaVersion := "2.13.0",
+    scalaVersion := "2.12.8",
```
Comment (renatocaval) [inline documentation/build.sbt]: Is that correct? Why going back to 2.12.8?

Comment (ignasi35) [reply documentation/build.sbt]: I think making `2.13.0` everywhere the default can happen on a separate PR.

It requires reviewing all `scripts/*` since `scripts/test-ff-212` uses the default so we must review those to ensure `2.12.x` is used explicitly.
