### PR TITLE
Run scripted tests on sbt 1.4.x + refactoring

### PR DESCRIPTION
**Pull request by mkurz**
As [suggested once by Dale](https://github.com/playframework/playframework/pull/9936#pullrequestreview-334442852) I now folded `scripts/test-scripted-13x` into `scripts/test-scripted`. I also can not see why we should have different scripts for different sbt versions... Also because this pull request now adds another sbt version,1.4.9, meaning the scripted tests will now be run against ~1.2.x,~ 1.3.x and 1.4.x.

I also defined fixed sbt versions in `.travis.yml`. Before that the job(s) that "_Run scripted tests (a/b/c) for sbt 1.x_" would just use the sbt version set by interplay (See [Line](https://github.com/sbt/sbt/blob/v1.4.6/main/src/main/scala/sbt/ScriptedPlugin.scala#L63) -> [Line](https://github.com/playframework/interplay/blob/3.0.0/src/main/scala/interplay/PlaySbtBuildBase.scala#L14) -> [Line](https://github.com/playframework/interplay/blob/3.0.0/src/main/scala/interplay/Versions.scala#L9)). IMHO setting the versions hardcoded in .travis.yml is more readable (took me a while to figure out the default comes from interplay), safer (what if interplay upgrades to 1.3.x or newer, but nobody updates the `.travis.yml` description, when looking at the tests someone may still thinks that the tests are running for 1.2.x) and also easier to maintain (we can quickly test new sbt versions by just updating .travis.yml instead of releasing and upgrading interplay).

### CODE REVIEW

**Comment by mkurz** [comment]
[Following scripted tests fail](https://travis-ci.com/github/playframework/playframework/jobs/475519183#L10428-L10439) when running with sbt 1.4, however this was expected by me, because sbt 1.4 support [is not done/merged yet](10648):
```
[error] 	play-sbt-plugin/dev-mode
[error] 	play-sbt-plugin/evolutions-auto-apply-false
[error] 	play-sbt-plugin/evolutions-auto-apply-true
[error] 	play-sbt-plugin/evolutions-multiple-databases
[error] 	play-sbt-plugin/generated-keystore
[error] 	play-sbt-plugin/http-backend-system-property
[error] 	play-sbt-plugin/maven-layout-twirl-reload
[error] 	play-sbt-plugin/multiproject
[error] 	play-sbt-plugin/play-position-mapper
[error] 	play-sbt-plugin/routes-compiler-source-mapping
[error] 	play-sbt-plugin/shutdown-downing
[error] 	play-sbt-plugin/shutdown-happy-path
```

File: .travis.yml [hunk 1]
```diff
@@ -27,7 +34,11 @@ install: jabba install $(jabba ls-remote "adopt@~1.$TRAVIS_JDK.0-0" --latest=pat
 stages:
   - validations
   - test
-  - test-sbt
+  - test-sbt-1.2.x
+  - cron-test-sbt-1.2.x
+  - cron-test-sbt-1.3.x
+  - cron-test-sbt-1.4.x
+  - cron-test-sbt-1.5.x
   - java8
```
Comment (ignasi35) [inline .travis.yml:42]: This build matrix is rather expensive. I would remove sbt 1.2 (superseded by 1.3) and sbt 1.5 (still RC)

File: .travis.yml [hunk 2]
```diff
@@ -55,65 +66,95 @@ jobs:
...
+      workspaces:
+        use: published-local
+    # Test against sbt 1.5.x, but only for cron builds
+    - stage: cron-test-sbt-1.5.x
+      name: "Run tests for 1.5.x and Scala 2.12.x"
+      script: scripts/test-scripted $SCRIPTED_SBT_1_5 $TEST_SCALA_2_12
+      workspaces:
+        use: published-local
+    - name: "Run tests for 1.5.x and Scala 2.13.x"
+      script: scripts/test-scripted $SCRIPTED_SBT_1_5 $TEST_SCALA_2_13
```
Comment (ignasi35) [inline .travis.yml:157]: these need a conditional checking the build is a CRON one.

Screenshot 2021-02-25 at 18 08 22

Comment (mkurz) [reply .travis.yml:157]: > these need a conditional checking the build is a CRON one.

Yes I know, this was intentional. My plan was:
1. Get #10711 merged
2. Restart Travis for this pull request here so _all_ sbt versions will be tested with the fixes in #10711
3. If successfull, add a separate commit with the cron config
4. Merge this pull request.

File: .travis.yml (hunk 1 above)
Comment (mkurz) [reply .travis.yml:42]: Alright, I will remove them in the next commit to this PR in which I will turn on the cron jobs as soon as #10711 got merged. See comment below https://github.com/playframework/playframework/pull/10655/files#r583106363

File: .travis.yml [hunk 3]
```diff
@@ -15,7 +15,14 @@ git:
...
     - secure: "NS2hMbBcmi6EF4QxtcNs4A2ZuNmIdLYQRJUWWejgnD4YtcsmoVjxrHRedqrnDdui4DyvaxWhg/3Uds23jEKTSbbh3ZphLO77BVgM2nUGUvVoa4i6qGF2eZFlIhq2G1gM700GPV7X4KmyjYi2HtH8CWBTkqP3g0An63mCZw/Gnlk="
-  matrix:
+    # These are the versions used for (scripted) tests. The versions Play is build with however are defined in interplay.
+    - SCRIPTED_SBT_1_2: "1.2.8"
+    - SCRIPTED_SBT_1_3: "1.3.13"
+    - SCRIPTED_SBT_1_4: "1.4.7"
+    - SCRIPTED_SBT_1_5: "1.5.0-M2"
+    - TEST_SCALA_2_12: "2.12.13"
+    - TEST_SCALA_2_13: "2.13.5"
+  jobs:
```
Comment (mkurz) [inline .travis.yml:25]: BTW: I changed `matrix` to `jobs` because `matrix` is just an alias:
https://github.com/travis-ci/travis-yml/blob/900f5f5aba2f3127e0eff16c5bf9b90abbfd4f9b/schema.json#L594-L598
[Travis CI docs](https://docs.travis-ci.com/user/build-matrix/#listing-individual-jobs) always use `jobs`, I never saw `matrix`.

**Comment by mkurz** [comment]
Backport #10723

**Comment by mkurz** [comment]
Now that #10711 got merged, I restarted the tests for this PR, let's see if all the tests pass when running against sbt 1.4

**Comment by mkurz** [comment]
Following scripted tests fail when running against sbt 1.4.x, but pass with 1.3.x
```
[error] (scripted) Failed tests:
[error] 	play-sbt-plugin/multiproject
[error] 	play-sbt-plugin/play-position-mapper
[error] 	play-sbt-plugin/routes-compiler-source-mapping
```

Challenge accepted :trollface:

**Comment by mkurz** [comment]
To make `play-sbt-plugin/play-position-mapper` work we need to wait for sbt 1.4.8, which should be released this weekend. I had to patch sbt:
https://github.com/sbt/sbt/pull/6352
1.4.x backport: https://github.com/sbt/sbt/pull/6356

File: .travis.yml (hunk 1 above)
Comment (mkurz) [reply .travis.yml]: I removed sbt 1.2 and 1.5-M2 from the build marix now.

File: .travis.yml (hunk 2 above)
Comment (mkurz) [reply .travis.yml]: The conditional checks are now in place.

File: dev-mode/sbt-plugin/src/main/scala/play/sbt/run/PlayReload.scala [hunk 4]
```diff
@@ -41,6 +100,28 @@ object PlayReload {
...
             .find(_.severity == Severity.Error)
+            .map(problem =>
+              // Starting with sbt 1.4.1, when a compilation error occurs, the Position of a Problem (which is contained within the Incomplete) will no longer refer
+              // to the mapped source file (e.g. until sbt 1.4.0 the Position would refer to "conf/routes" when a compilation error actually happened
+              // in "target/scala-2.13/routes/main/router/Routes.scala").
+              // That's caused by https://github.com/sbt/zinc/pull/931: The file causing the compilation error is not transformed via the sourcePositionMappers config
+              // anymore before adding it to "allProblems", the field that eventually gets used by the Incomplete. (The transformation still takes place to show
+              // the mapped source file in the logs) Play however needs to know the mapped source file to display it in it's error pages for a nice dev experience.
+              // So the solution is that Play itself will try to transform the source file to the mapped file by running it "through" sourcePositionMappers:
+              Project
```
Comment (mkurz) [inline dev-mode/sbt-plugin/src/main/scala/play/sbt/run/PlayReload.scala:111]: I think the comment says it all... So since https://github.com/sbt/zinc/pull/931 ([which](https://github.com/sbt/zinc/compare/v1.4.0...v1.4.1) made it into [sbt 1.4.1](https://github.com/sbt/sbt/compare/v1.4.0...v1.4.1#diff-ad2642dc77b3679e4ad2c7d3b2f59a2dcf48c1bf5b93a558a4fa44828315a34cR17)) the left `Incomplete` of following `compileResult`
https://github.com/playframework/playframework/blob/47f277b5357455cb8759e4b4fe0ebe3bc605368b/dev-mode/sbt-plugin/src/main/scala/play/sbt/run/PlayReload.scala#L63-L67 comes with Positions which are _not_ transformed by the sourcePositionMappers config anymore. Here is the relevant code after that referenced pull request got applied for better context:
https://github.com/sbt/zinc/blob/v1.4.1/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/LoggedReporter.scala#L131-L139
So since 1.4.1 sbt only transforms the position for log outputs... which is a problem for Play, so we have to make the Positions run through the sourcepositionmappers ourselves to show users the correct original soure of a problem in the error pages...

File: dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/build.sbt.1 [hunk 5]
```diff
@@ -19,14 +19,10 @@ lazy val root = (project in file("."))
...
       val destination = target.value / dest
 
-      println(s"Preparing to run request to $path...")
-
-      Future {
-        println(s"Firing request to $path...")
-        val (status, body) = ScriptedTools.callUrl(path)
-        println(s"Resource at $path returned HTTP $status")
-        IO.write(destination, body)
-      }
```
Comment (mkurz) [inline dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/build.sbt.1:29]: No need to wrap this in a `Future` for _these tests here_... This was a mistake from beginning when I just copy/pasted the `makeRequestAndRecordResponseBody` task from the [`shutdown-happy-path` scripted test](https://github.com/playframework/playframework/blob/2.8.7/dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/shutdown-happy-path/build.sbt#L58-L63) where that Future is actually needed because it is [a different test case](https://github.com/playframework/playframework/blob/2.8.7/dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/shutdown-happy-path/test#L111-L120).
As a result, in the test, we can also remove the 2 and 5 seconds `sleep`s after calling the command because now its blocking.

File: dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/test [hunk 6]
```diff
@@ -30,96 +30,152 @@ $ delete build.sbt.1
 ################
 $ copy-file conf/application.conf application.conf.good
 $ copy-file application.conf.bad conf/application.conf
+# Give CI/docker/Java thread enough time to detect file change
+$ sleep 1200
```
Comment (mkurz) [inline dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/test:34]: After the `copy-file` we need to give [the Java thread that reacts to file system changes](https://github.com/openjdk/jdk/blob/jdk8-b120/jdk/src/solaris/classes/sun/nio/fs/LinuxWatchService.java#L41-L44) a bit time... This actually fixes [the flaky tests that showed up the last days in the cron jobs](https://github.com/playframework/playframework/issues/10742).
(Or maybe it's because how things run inside Travis' docker containers and how processes/threads are handled within it... not 100% sure, however that timeout fixes the flakyness)

File: dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/test [hunk 7]
```diff
@@ -30,96 +30,152 @@ $ delete build.sbt.1
...
 > makeRequestAndRecordResponseBody / appconf-fail.txt
 # First request takes a bit longer, therefore 5 seconds
-$ sleep 5000
```
Comment (mkurz) [inline dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/test:35]: Like mentioned `makeRequestAndRecordResponseBody` is blocking now, no need anymore for that `sleep`.

File: dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/test [hunk 8]
```diff
@@ -30,96 +30,152 @@ $ delete build.sbt.1
...
 > checkLinesPartiallyNotContain blacklist.txt target/routes-fail.txt
 $ copy-file routes.good conf/routes
+# Give CI/docker/Java thread enough time to detect file change
+$ sleep 1200
+> verifyResourceContains / 200 "app compiles and runs!"
+
+###################################################################################################################
+# Invalid routes (parsing the routes file is OK, but compiling target/scala-*/routes/main/router/Routes.scala fails)
+# Actually this tests if the sourcePositionMappers set up for the routes compiler is called and works correctly
+###################################################################################################################
```
Comment (mkurz) [inline dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/test:62]: For the routes file and twirl templates (see further below) tests were added, where parsing that files is OK, but compiling their generated scala files fails... That tests make sure that the sourcePositionMappers get called in sbt 1.4.1+ and provide the correct original source file of the problem, see [comment above](#r592454311).

File: dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject/build.sbt [hunk 9]
```diff
@@ -64,7 +64,28 @@ TaskKey[Unit]("checkPlayCompileEverything") := {
     base / "playmodule" / "app" / "PlayModule.scala",
     base / "transitive" / "app" / "Transitive.scala"
   )
-  val allSources = analyses.flatMap(_.relations.allSources).map(_.toPath).sorted.map(_.toFile)
+  val allSources = analyses.flatMap(_.relations.allSources).map(_ match {
```
Comment (mkurz) [inline dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject/build.sbt:67]: `allSources` returns `VirtualFile`s in sbt 1.4 (which has no `toPath` method) but a Java `File` in sbt <= 1.3... Therefore I had to apply the same workaround in this test we used in PR 10648: https://github.com/playframework/playframework/pull/10648/files#diff-e1d77acde8f8aee39e58b112462d82fdcbc8c2920092be5af01ed5b3a92ca64b

File: dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-injected-routes-compilation-with-request-passed/build.sbt [hunk 10]
```diff
@@ -5,6 +5,7 @@ lazy val root = (project in file("."))
   .enablePlugins(PlayJava)
 
 libraryDependencies ++= Seq(guice, specs2 % Test)
+libraryDependencies += "org.scala-lang.modules" %% "scala-collection-compat" % "2.3.2" // can be removed when dropping Scala 2.12
```
Comment (mkurz) [inline dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-injected-routes-compilation-with-request-passed/build.sbt:8]: These an all changes below make the scripted tests behave on Scala 2.13 (until now they were just run with Scala 2.12...)

File: dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-source-mapping/build.sbt [hunk 11]
```diff
@@ -1,52 +0,0 @@
...
-
-sources in (Compile, routes) := Seq(baseDirectory.value / "routes")
-
-InputKey[Unit]("allProblemsAreFrom") := {
-  val args   = Def.spaceDelimited("<source> <line>").parsed
-  val base   = baseDirectory.value
-  val source = base / args(0)
-  val line   = Integer.parseInt(args(1))
-  val errors = Incomplete
-    .allExceptions(assertLeft(assertSome(Project.runTask(compile in Compile, state.value))._2.toEither))
```
Comment (mkurz) [inline dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-source-mapping/build.sbt:24]: I removed that test because it will never succeed anymore in sbt 1.4.1+ because Positions returned by the incomplete will not be transformed anymore by the sourcepositionmappers, see [comment above](#r592454311).

File: dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/show-versions/test [hunk 12]
```diff
@@ -0,0 +1,7 @@
+# Useful so we know if the CI jobs use the expected versions
```
Comment (mkurz) [inline dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/show-versions/test:1]: I think it's useful to check Travis output if we are running the expected versions... IMHO this was not possible before.

File: project/BuildSettings.scala [hunk 13]
```diff
@@ -376,7 +376,6 @@ object BuildSettings {
       "-XX:MaxMetaspaceSize=300m",
       "-XX:HeapDumpPath=/tmp/",
       "-XX:+HeapDumpOnOutOfMemoryError",
-      s"-Dscala.version=$scala212",
```
Comment (mkurz) [inline project/BuildSettings.scala:379]: This [gets set](#diff-2a2bc9b120b7a543ded4151ad37ae49ab9b2f8deb533b142c01e01d9f5921838R19) by `script/test-scripted` now.

File: scripts/publish-local [hunk 14]
```diff
@@ -12,7 +12,7 @@ rm -rf $HOME/.ivy2/local
 end clean "CLEANED IVY LOCAL REPO"
 
 start publish-local "CROSS-PUBLISHING PLAY LOCALLY FOR SBT SCRIPTED TESTS"
-runSbt +publishLocal
+runSbt ";crossScalaVersions;crossSbtVersions;+publishLocal"
```
Comment (mkurz) [inline scripts/publish-local:15]: Just adding some output for debugging...

**Comment by mkurz** [comment]
@ignasi35 @octonato This pull request is finally ready to review!

As an example how a cron build will look like (except without sbt 1.2) you can have a look at 
https://travis-ci.com/github/playframework/playframework/builds/219526837
which is the build of this commit:
image
(the commit before I added the cron conditions)

File: .travis.yml [hunk 15]
```diff
@@ -31,7 +36,9 @@ install: jabba install $(jabba ls-remote "adopt@~1.$TRAVIS_JDK.0-0" --latest=pat
 stages:
   - validations
   - test
-  - test-sbt
+  - test-sbt-1.3.x
+  - cron-test-sbt-1.3.x
+  - cron-test-sbt-1.4.x
```
Comment (ignasi35) [inline .travis.yml:41]:
```suggestion
  - test-sbt-1.3.x-2.12
  - cron-test-sbt-1.3.x-2.13
  - cron-test-sbt-1.4.x
```

Indicating the difference (scala version) to make it clearer what's the version tested on every PR.

File: .travis.yml [hunk 16]
```diff
@@ -59,64 +66,77 @@ jobs:
...
+        use: published-local
+    # Test against sbt 1.4.x, but only for cron builds
+    - stage: cron-test-sbt-1.4.x
+      name: "Run tests for 1.4.x and Scala 2.12.x"
+      script: scripts/test-scripted $SCRIPTED_SBT_1_4 $TEST_SCALA_2_12
+      if: type = cron
+      workspaces:
+        use: published-local
+    - name: "Run tests for 1.4.x and Scala 2.13.x"
+      script: scripts/test-scripted $SCRIPTED_SBT_1_4 $TEST_SCALA_2_13
```
Comment (ignasi35) [inline .travis.yml:139]: This is rather expensive and I'm not 100% sure we should extend the support matrix in all possible axis (JDK8/11, sbt1.3/1.4, scala2.12/2.13).

I think running _only_ 1.4.x for 2.13 could be enough. I think users of sbt 1.4 may be more likely to be early adopters in general and, therefore, users of 2.13 already.

Again, not sure whether we should keep both jobs or not...

File: dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/test (hunk 6 above)
Comment (ignasi35) [reply dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/test:34]: `1200` is a very weird-looking duration. 😅
(no need to change it!)

File: dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/test [hunk 17]
```diff
@@ -30,96 +30,152 @@ $ delete build.sbt.1
 ################
 $ copy-file conf/application.conf application.conf.good
 $ copy-file application.conf.bad conf/application.conf
+# Give CI/docker/Java thread enough time to detect file change
+$ sleep 1200
 > makeRequestAndRecordResponseBody / appconf-fail.txt
 # First request takes a bit longer, therefore 5 seconds
```
Comment (ignasi35) [inline dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/test:36]: This comment is obsolete (the sleep is gone)

File: dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/test (hunk 8 above)
Comment (ignasi35) [reply dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/test:62]: Nice addition. Thanks @mkurz

File: dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/test [hunk 18]
```diff
@@ -30,96 +30,152 @@ $ delete build.sbt.1
...
 > checkLinesPartiallyNotContain blacklist.txt target/twirl-fail.txt
 $ copy-file index.scala.html.good app/views/index.scala.html
+# Give CI/docker/Java thread enough time to detect file change
+$ sleep 1200
+> verifyResourceContains / 200 "app compiles and runs!"
+
+#############################################################################################################################################
+# Invalid twirl template (parsing index.scala.html file is OK, but compiling target/scala-*/twirl/main/views/html/index.template.scala fails)
+# Actually this tests if the sourcePositionMappers set up by sbt-twirl is called and works correctly
+#############################################################################################################################################
```
Comment (ignasi35) [inline dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/test:108]: These comments are great. Help the maintenance of the tests as they explain the expectation and use case very clearly. 👏🏼

File: dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/show-versions/test (hunk 12 above)
Comment (ignasi35) [reply dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/show-versions/test:1]: Nice trick!

**Review by ignasi35 — APPROVED** [review]
This is great work! Thanks @mkurz 

I only have a concern re the cost of running so many scripted tests in the CRON jobs. I'll merge as is but we should keep an eye on the weekend cron jobs to get a better idea of how much cost/benefit this brings.

File: .travis.yml (hunk 15 above)
Comment (ignasi35) [reply .travis.yml:41]: Not a blocker. Let's solve this elsewhere.

File: dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/test (hunk 17 above)
Comment (ignasi35) [reply dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/test:36]: I was referring to ` # First request takes a bit longer, therefore 5 seconds `

**Comment by mkurz** [comment]
@ignasi35 thanks a lot for the review! I removed the obsolete comment.

> I only have a concern re the cost of running so many scripted tests in the CRON jobs

Like you said, lets merge and observe, we can always change/remove jobs from the matrix.
