### PR TITLE
[2.7.x] Remove incorrect documentation 

### PR DESCRIPTION
**Pull request by wsargent**
Fixes an out of date comment for 2.7.x branch. This was changed in wsargent/playframework@ccda638#diff-8c92eba25113fadb7c0c63d00ee6a572L42 but the explicit factory comment was not removed.

This was originally https://github.com/playframework/playframework/pull/9085 but was incorrectly created from the playframework branch (and then couldn't be merged because of build breakage, and could not be force pushed).

### CODE REVIEW

**Comment by wsargent** [comment]
Another formatting error :-/

https://travis-ci.com/playframework/playframework/jobs/185717558#L3722

**Comment by marcospereira** [comment]
I have fixed the code format issue. Sorry about the noisy, @wsargent. I can see the build for #9072 backport was failing: https://travis-ci.com/playframework/playframework/builds/103495345

Hopefully, this will be okay now.

**Comment by wsargent** [comment]
```
[error] /home/travis/build/playframework/playframework/core/play-microbenchmark/src/test/scala/play/microbenchmark/it/HelloWorldBenchmark.scala:121: type mismatch;
[error]  found   : (String, javax.net.ssl.SSLSession) => Boolean
[error]  required: javax.net.ssl.HostnameVerifier
[error]               .hostnameVerifier((s: String, sslSession: SSLSession) => true)
[error]                                                                     ^
[error] one error found
[error] (Play-Microbenchmark/test:compileIncremental) Compilation failed
[error] Total time: 19 s, completed Mar 19, 2019 10:37:23 AM
```

again not me >:-(

**Comment by mkurz** [comment]
@wsargent @marcospereira The problem was caused by #8990. On master branch no problem, because there is no Scala 2.11 anymore.

**Comment by marcospereira** [comment]
Thanks, @mkurz!
